# Based off Tony Banters alacritty config (TokyoNight colors)
[window]
opacity=0.8
blur=true

[window.padding]
y = 6 
x = 6  

[font]
size = 12
#normal = { family = "Terminess Nerd Font", style = "Heavy" }
normal = { family = "Iosevka Nerd Font", style = "Heavy" }

[colors.bright]
black   = "#444b6a"
blue    = "#7da6ff" 
cyan    = "#0db9d7"
green   = "#b9f27c"
magenta = "#bb9af7"
red     = "#ff7a93"
white   = "#acb0d0"
yellow  = "#ff9e64"

[env]
TERM = "xterm-256color"

[cursor]
style = { shape="Beam", blinking="On" }

[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[colors.normal]
black   = "#15161e"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#a9b1d6"
